site_name: Picovico - API Documentation
theme: readthedocs
repo_url: https://github.com/picovico/apidocs
site_author: Picovico Inc.
site_favicon: http://www.picovico.com/app/assets/img/favicon.ico?v=102
docs_dir: docs
pages:
 - [index.md, Home]
 - [login-flow.md, Login Flow]
 - [videos.md, Videos]
 - [photos.md, Photos]
 - [photos/photo-details.md, Photo Details]
 - [musics.md, Musics & Audio Library]
 - [musics/music-details.md, Music Details]
 - [styles.md, Styles]
