site_name: Picovico - API Documentation
theme: readthedocs
repo_url: https://github.com/picovico/apidocs
site_author: Picovico Inc.
site_favicon: http://www.picovico.com/app/assets/img/favicon.ico?v=102
docs_dir: docs
pages:
 - [index.md, Home]
 - [login-flow.md, Login Flow]
 - [videos/index.md, Videos]
 - [videos/details.md, Videos]
 - [photos/index.md, Photos]
 - [photos/details.md, Photos]
 - [musics/index.md, Musics & Audio Library]
 - [musics/details.md, Musics & Audio Library]
 - [styles.md, Styles]
